# Hyperperameter Tuning

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv(r"C:\Users\imrat\OneDrive\Desktop\data_science_all_uses_items\Data_set\Churn_Modelling.csv")
dataset.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [3]:
dataset.drop(columns=["RowNumber","CustomerId","Surname" ,"Geography","Gender"],inplace=True)

In [4]:
dataset.head(3)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1

In [5]:
dataset.isnull().sum()

CreditScore        0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
input_data = dataset.iloc[:,:-1]
output_data = dataset.iloc[:,-1]

In [7]:
from sklearn.preprocessing import StandardScaler

In [10]:
ss = StandardScaler()
input_data = pd.DataFrame(ss.fit_transform(input_data),columns=input_data.columns)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(input_data,output_data,test_size=0.2,random_state=42)

In [13]:
import tensorflow

In [16]:
from keras.layers import Dense
from keras.regularizers import L2
from keras.callbacks import EarlyStopping
from keras.models import Sequential

In [19]:
ann = Sequential()

In [21]:
ann.add(Dense(6,input_dim=8,activation="relu",kernel_regularizer=L2(l2=0.01)))
ann.add(Dense(5,activation="relu",kernel_regularizer=L2(l2=0.01)))
ann.add(Dense(4,activation="relu",kernel_regularizer=L2(l2=0.01)))
ann.add(Dense(3,activation="relu",kernel_regularizer=L2(l2=0.01)))
ann.add(Dense(2,activation="relu",kernel_regularizer=L2(l2=0.01)))
ann.add(Dense(1,activation="sigmoid"))

In [24]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [25]:
ann.fit(x_train,y_train,batch_size=100,epochs=50,validation_data=(x_test,y_test),callbacks=EarlyStopping())

Epoch 1/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7945 - loss: 0.8346 - val_accuracy: 0.8035 - val_loss: 0.7736
Epoch 2/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.7125 - val_accuracy: 0.8035 - val_loss: 0.6461
Epoch 3/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.6219 - val_accuracy: 0.8035 - val_loss: 0.5880
Epoch 4/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.5832 - val_accuracy: 0.8035 - val_loss: 0.5572
Epoch 5/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.5563 - val_accuracy: 0.8035 - val_loss: 0.5317
Epoch 6/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.5340 - val_accuracy: 0.8035 - val_loss: 0.5116
Epoch 7/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.5191 - val_accuracy: 0.8035 - val_loss: 0.4994
Epoch 8/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.5097 - val_accuracy: 0.8035 - val_loss: 0.4916
Epoch 9/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.5033 - val_accuracy: 0.8035 - val_loss: 0.4856
Epoch 10/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4980 - val_accuracy: 0.8035 - val_loss: 0.4823
Epoch 11/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4940 - val_accuracy: 0.8035 - val_loss: 0.4775
Epoch 12/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4904 - val_accuracy: 0.8035 - val_loss: 0.4737
Epoch 13/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4869 - val_accuracy: 0.8035 - val_loss: 0.4709
Epoch 14/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4831 - val_accuracy: 0.8035 - val_loss: 0.4671
Epoch 15/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4792 - val_accuracy: 0.8035 - val_loss: 0.4639
Epoch 16/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4755 - val_accuracy: 0.8035 - val_loss: 0.4600
Epoch 17/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4721 - val_accuracy: 0.8035 - val_loss: 0.4578
Epoch 18/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4691 - val_accuracy: 0.8035 - val_loss: 0.4561
Epoch 19/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8280 - loss: 0.4666 - val_accuracy: 0.8425 - val_loss: 0.4543
Epoch 20/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8335 - loss: 0.4641 - val_accuracy: 0.8435 - val_loss: 0.4528
Epoch 21/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8359 - loss: 0.4623 - val_accuracy: 0.8410 - val_loss: 0.4509
Epoch 22/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8370 - loss: 0.4601 - val_accuracy: 0.8435 - val_loss: 0.4494
Epoch 23/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8370 - loss: 0.4587 - val_accuracy: 0.8475 - val_loss: 0.4485
Epoch 24/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8386 - loss: 0.4573 - val_accuracy: 0.8440 - val_loss: 0.4470
Epoch 25/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8399 - loss: 0.4558 - val_accuracy: 0.8480 - val_loss: 0.4464
Epoch 26/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8418 - loss: 0.4544 - val_accuracy: 0.8520 - val_loss: 0.4466

In [26]:
from sklearn.metrics import accuracy_score

In [28]:
prd = ann.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [29]:
prd_data = []
for i in prd:
    if i[0]>0.5:
        prd_data.append(1)
    else:
        prd_data.append(0)

In [30]:
accuracy_score(y_test,prd_data)*100

85.2

In [31]:
prd1 = ann.predict(x_train)

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [34]:
prd_data1 = []
for i in prd1:
    if i[0]>0.5:
        prd_data1.append(1)
    else:
        prd_data1.append(0)

In [35]:
accuracy_score(y_train,prd_data1)*100

84.4375